name: Library Build Stardust

on:
    push:
        branches: [feat/stardust]
    pull_request:
        branches: [feat/stardust]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - name: npm 7
              run: npm install -g npm@7
            - name: Build
              run: |
                  npm install
                  npm run dist --workspaces
