name: Library Build Main/Dev

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.16
              uses: actions/setup-node@v2
              with:
                  node-version: "16.16"
            - name: npm 8.18
              run: npm install -g npm@8.18
            - name: Build
              run: |
                  npm install
                  npm run dist --workspaces
